name: CI

on:
  push:
    branches:
      - main
      - 'feature*'
      - 'bugfix*'
      - 'hotfix*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run ruff
        run: uv run ruff check addons/mixer tests extra

      - name: Run mypy
        run: uv run mypy addons/mixer
        continue-on-error: true

      - name: Build docs
        run: uv run sphinx-build -b html docs docs/_build/html

      - name: Run tests
        if: |
          contains(github.ref, 'main') ||
          contains(github.ref, 'develop') ||
          github.event_name == 'pull_request'
        run: |
          # Run basic pytest tests (without Blender integration)
          uv run pytest tests/test_test.py -v
        continue-on-error: true

      - name: Upload build artifacts
        if: contains(github.ref, 'main')
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/_build/html
