name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  MIXER_BASH_EXE: bash
  VRTIST_PORT: 25600
  MIXER_TEST_OUTPUT: logs/tests
  MIXER_BLENDER_EXE_PATH: blender-3.3.19-windows-x64/blender.exe
  MIXER_PYTHON_3_PATH: blender-3.3.19-windows-x64/3.3/python/bin/python.exe

jobs:
  pre_release:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pep8-naming mypy sphinx sphinx-rtd-theme requests --constraint requirements-dev.txt 

      - name: Run ruff
        run: |
          ruff -v addons/mixer tests extra

      - name: Run mypy
        run: |
          mypy mixer
        continue-on-error: true

      - name: Build docs
        run: |
          sphinx-build -b html docs docs/_build/html
          rm -rf docs/_build/doctree

      - name: Zip files
        run: |
          cp CHANGELOG.md README.md LICENSE mixer/
          rm -rf mixer/blender_data/tests/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blender_mixer
          path: |
            docs/_build
            mixer

  startup_windows:
    needs: pre_release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download and extract Blender
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://mirrors.ocf.berkeley.edu/blender/release/Blender3.3/blender-3.3.19-windows-x64.zip" -OutFile "blender.zip"
          Expand-Archive -Path "blender.zip" -DestinationPath .

      - name: Run tests
        shell: bash
        run: |
          mkdir -p $MIXER_TEST_OUTPUT
          $MIXER_PYTHON_3_PATH -m pip install unittest-xml-reporting parameterized unittest2 xmlrunner
          $MIXER_BLENDER_EXE_PATH --background --python-exit-code 1 --python gitlab/install_mixer.py
          if [ -f mixer/blender_data/tests/ci.py ]; then
            exit 0
          fi
          $MIXER_BLENDER_EXE_PATH --background --python-exit-code 1 --python mixer/blender_data/tests/ci.py
          $MIXER_PYTHON_3_PATH -m xmlrunner discover --verbose tests.vrtist -o $MIXER_TEST_OUTPUT
          $MIXER_PYTHON_3_PATH -m xmlrunner discover --verbose tests.broadcaster -o $MIXER_TEST_OUTPUT
          $MIXER_PYTHON_3_PATH -m xmlrunner discover --verbose tests.blender -o $MIXER_TEST_OUTPUT
